config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :site_portfolios, except: [:show]
  get 'portfolio/:id', to: 'site_portfolios#show', as: 'portfolio_show'

  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'helloworld', to: 'pages#helloworld'


  resources :blogs do
	  member do
		  get :toggle_status
		end
	end
  
  root to: 'pages#home'
  
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_application_footer.html.erb
<div class="mastfoot">
    <div class="inner">
	    <p>_application_footer</p>
	    </div>
	</div>

app/views/shared/_application_nav.html.erb
<div class="masthead clearfix">
    <div class="inner">
        <h3 class="masthead-brand">Chris Rees</h3>
        <nav class="nav nav-masthead">
			<%= link_to "Home", root_path, class: 'nav-link' %>
			<%= link_to "About", about_path, class: 'nav-link' %>
			<%= link_to "Contact", contact_path, class: 'nav-link' %>
			<%= link_to "Blog", blogs_path, class: 'nav-link' %>
			<%= link_to "Portfolios", site_portfolios_path, class: 'nav-link' %>
			<%= login_helper('nav-link') %>
            </nav>
        </div>
    </div>

app/views/shared/_nav.html.erb
       <div class="<%= location %>">
	       <div><%= link_to "Home", root_path %></div>
	       <div><%= link_to "About", about_path %></div>
	       <div><%= link_to "Contact", contact_path %></div>
	       <div><%= link_to "Blog", blogs_path %></div>
	       <div><%= link_to "Portfolios", site_portfolios_path %></div>
       </div>