config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :site_portfolios, except: [:show]
  get 'portfolio/:id', to: 'site_portfolios#show', as: 'portfolio_show'

  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'helloworld', to: 'pages#helloworld'


  resources :blogs do
	  member do
		  get :toggle_status
		end
	end
  
  root to: 'pages#home'
  
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/site_portfolio.rb
class SitePortfolio < ApplicationRecord
has_many :technologies
	validates_presence_of :title, :subtitle, :body, :main_image, :thumb_image
	accepts_nested_attributes_for :technologies, 
		reject_if: lambda { |attrs| attrs['name'].blank? }
		


	def self.angular
		where(subtitle: "AngularJS")
	end
	scope :ruby_on_rails_portfolio_items, -> { where(subtitle: "Ruby on Rails") }
	
	after_initialize :set_defaults
		
		
	def set_defaults
		self.main_image ||= "http://placehold.it/600x400"
		self.thumb_image ||=  "http://placehold.it/350x200"
	end
		
end

app/controllers/site_portfolios_controller.rb
class SitePortfoliosController < ApplicationController
	before_action :set_portfolio_item, only: [:edit, :show, :update, :destroy]
	access all: [:show, :index], user: {except: [:destroy, :edit, :update, :new, :create]}, site_admin: :all
	layout 'site_portfolio'
	def index
		@portfolio_items = SitePortfolio.all
		end
	def new
		@portfolio_item = SitePortfolio.new
		3.times { @portfolio_item.technologies.build }
		end
		
	def create
	    @site_portfolio =  SitePortfolio.new(site_portfolio_params)
		    respond_to do |format|
			    if @site_portfolio.save
			        format.html { redirect_to site_portfolios_path, notice: 'Portfolio successfully created.' }
				    else
				    format.html { render :new }
				end
			end
		end
    def edit
	   	end
	def update
	    respond_to do |format|
		    if @portfolio_item.update(site_portfolio_params)
		        format.html { redirect_to site_portfolios_path, notice: 'Blog was successfully updated.' }
			    else
		        format.html { render :edit }
			    end
		    end
		end
	def show
		end
	def destroy
		@portfolio_item.destroy
			respond_to do |format|
				format.html { redirect_to site_portfolios_url, notice: 'Portolio item was successfully destroyed.' }
    		end
		end
	private 
	
	def site_portfolio_params
		params.require(:site_portfolio).permit(
		:title, 
		:subtitle, 
		:image,
		:body, 
		technologies_attributes: [:name])
		end
	def set_portfolio_item
		@portfolio_item = SitePortfolio.find(params[:id])
		end
	end

app/helpers/site_portfolios_helper.rb
module SitePortfoliosHelper
end

app/views/site_portfolios/_form.html.erb
<%= form_for(@portfolio_item) do |f| %>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
    </div>
    
  <div class="field">
    <%= f.label :subtitle %>
    <%= f.text_field :subtitle %>
    </div>
    
  <div class="field">
    <%= f.label :body %>
    <%= f.text_field :body %>
    </div>
  <ul>
	  <%= f.fields_for :technologies do |t| %>
	  <li>
	  	<%= t.label :name %>
	  	<%= t.text_field :name %>
	  </li>
	  <% end %>
  </ul>  

   <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/site_portfolios/_portfolio_item.html.erb
<p> <%= link_to portfolio_item.title, portfolio_show_path(portfolio_item) %> </p>
<p> <%= portfolio_item.subtitle %> </p>
<p> <%= portfolio_item.body %> </p>
<%= image_tag portfolio_item.thumb_image unless portfolio_item.thumb_image.nil? %>
<%= link_to "Edit", edit_site_portfolio_path(portfolio_item) if logged_in?(:site_admin) %>
<%= link_to 'Delete portfolio item', site_portfolio_path(portfolio_item), method: :delete, data: { confirm: 'Are you sure?' } if logged_in?(:site_admin) %>

app/views/site_portfolios/edit.html.erb
<h1>Edit a Portfolio Item</h1>

<%=render 'form', portfolio_item: @portfolio_item %>

app/views/site_portfolios/index.html.erb
<h1> Portfolio Items </h1>

<%= link_to "Create New Item", new_site_portfolio_path if logged_in?(:site_admin) %>

<%= render partial: 'portfolio_item', collection: @portfolio_items %>

app/views/site_portfolios/new.html.erb
<h1>Create a new Portfolio Item</h1>

<%=render 'form', portfolio_item: @portfolio_item %>

app/views/site_portfolios/show.html.erb
<%= image_tag @portfolio_item.main_image %>

<h1><%= @portfolio_item.title %></h1>

<h3><%= @portfolio_item.subtitle %></h3>

<p><%= @portfolio_item.body %></p>


<h2>Technologies Used:</h2>

<% @portfolio_item.technologies.each do |t| %>
<p><%= t.name %></p>

<% end %>